#! /bin/sh

$HOME/Scripts/tmux-startup &

ws1= #f120
ws2= #f0ac
ws3= #f0e0
ws4= #f121
ws5= #f016
ws6= #f115
ws7= #f144

bspc monitor -d $ws1 $ws2 $ws3 $ws4 $ws5 $ws6 $ws7

bspc config border_width         1
bspc config window_gap           0
bspc config focus_follows_pointer true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a st-256color:sys_info desktop='^1'
bspc rule -a st-256color:comm desktop='^3'

bspc rule -a brave desktop='^2'

bspc rule -a Godot desktop='^4'

bspc rule -a libreoffice-startcenter desktop='^5'

bspc rule -a Gimp desktop='^7' state=floating follow=on
bspc rule -a Steam desktop='^7'
bspc rule -a Kodi desktop='^7'
bspc rule -a Lutris desktop='^7'

bspc rule -a mpv state=floating
bspc rule -a Qalculate-gtk state=floating
bspc rule -a Gsimplecal state=floating
bspc rule -a Zathura state=tiled

bspc rule -a st-256color:scratchpad sticky=on state=floating

bspc rule -a "OPENGL test" state=floating

panel &
