#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

[ -f ~/.Xresources ] && xrdb -merge ~/.Xresources

envfile="$HOME/.gnupg/gpg-agent.env"
if [ -e "$envfile" ] && kill -0 "$(grep GPG_AGENT_INFO "$envfile" | cut -d: -f 2)" 2>/dev/null; then
    eval "$(cat "$envfile")"
else
    eval "$(gpg-agent --daemon --enable-ssh-support --write-env-file "$envfile")"
fi
export GPG_AGENT_INFO # the env file does not contain the export statement
export SSH_AUTH_SOCK # enable gpg-agent for ssh

#mpd &
numlockx &
sxhkd &
xsetroot -cursor_name left_ptr &
feh --bg-scale ~/.backgrounds/i3-background.png &

# exec gnome-session
# exec startkde
# exec startxfce4
# ...or the Window Manager of your choice
# exec enlightenment_start
# exec xterm
# exec $1
# exec tdm
# exec dbus-launch awesome
# exec dwm
# exec dbus-launch i3
# exec enlightenment_start
exec bspwm
