#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

[ -f ~/.Xresources ] && xrdb -merge ~/.Xresources

envfile="$HOME/.gnupg/gpg-agent.env"
if [ -e "$envfile" ] && kill -0 "$(grep GPG_AGENT_INFO "$envfile" | cut -d: -f 2)" 2>/dev/null; then
    eval "$(cat "$envfile")"
else
    eval "$(gpg-agent --daemon --enable-ssh-support )"
fi
export GPG_AGENT_INFO # the env file does not contain the export statement
export SSH_AUTH_SOCK # enable gpg-agent for ssh

# Set XDG_CONFIG_HOME properly
XDG_CONFIG_HOME=$HOME/.config
export XDG_CONFIG_HOME

sxhkd &
xsetroot -cursor_name left_ptr &
feh --bg-scale ~/.backgrounds/Floating-Tree-Abstract-Wallpaper.jpg &

exec bspwm
