#!/bin/sh

# Modified version of script found online.
# Cannot recall or find original source

# This shell script shows the network speed, both received and transmitted.

# Usage: net_speed.sh interface
#   e.g: net_speed.sh eth0

# Global variables
interface=enp3s0
received_bytes=""
old_received_bytes=""
transmitted_bytes=""
old_transmitted_bytes=""

# This function parses /proc/net/dev file searching for a line containing $interface data.
# Within that line, the first and ninth numbers after ':' are respectively the received and transmited bytes.
get_bytes(){
    line=$(cat /proc/net/dev | grep $interface | cut -d ':' -f 2 | awk '{print "received_bytes="$1, "transmitted_bytes="$9}')

    eval $line
}

# Function which calculates the speed using actual and old byte number.
# Speed is shown in KByte per second when greater or equal than 1 KByte per second.
# This function should be called each second.
get_velocity(){
    value=$1
    old_value=$2

    let vel=$value-$old_value
    let velKB=$vel/1024

    if [ $velKB != 0 ];
    then
        echo -n "$velKB KB/s";
    else
        echo -n "$vel B/s";
    fi
}

# Get initial values.
get_bytes
old_received_bytes=$received_bytes
old_transmitted_bytes=$transmitted_bytes

# Allow time for comparison
sleep 1

# Get new transmitted and received byte number values.
get_bytes

# Calculates speeds.
vel_recv=$(get_velocity $received_bytes $old_received_bytes)
vel_trans=$(get_velocity $transmitted_bytes $old_transmitted_bytes)

# echo results
echo -e "\uf063 $vel_recv \uf062 $vel_trans"
